/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package laboratorio2;

import laboratorio2.number.index;

public class App {

    public static void main(String[] args) {

    }
}
